export const CURRENT_ANIMATE = 'CURRENT_ANIMATE';



export const REQUEST_LOTTONUMS = 'REQUEST_LOTTONUMS';
export const FETCH_LOTTONUMS = 'FETCH_LOTTONUMS';
export const RECEIVE_LOTTONUMS = 'RECEIVE_LOTTONUMS';

